const HAINAN_CENTER=[19.15,109.73];
const BOUNDS={minLat:17.75,maxLat:20.55,minLon:108.20,maxLon:111.45};
const API='https://marine-api.open-meteo.com/v1/marine';
const BOUNDARY_URL='https://raw.githubusercontent.com/panyanbin/gcoord/master/map/%E6%B5%B7%E5%8D%97%E7%9C%81_460000.json';
const VARIABLES=['sea_surface_temperature','ocean_current_velocity','ocean_current_direction','wave_height','wave_direction','wave_period'];
const LAYERS={sst:{label:'Sea surface temperature · °C',unit:'°C SST',range:[22,34],ticks:['22','25','28','31','34'],key:'sea_surface_temperature',dec:1},wave:{label:'Significant wave height · m',unit:'m wave',range:[0,4],ticks:['0','1','2','3','4'],key:'wave_height',dec:2},current:{label:'Ocean current velocity · km/h',unit:'km/h current',range:[0,3],ticks:['0','0.75','1.5','2.25','3'],key:'ocean_current_velocity',dec:2},period:{label:'Wave period · s',unit:'s period',range:[2,14],ticks:['2','5','8','11','14'],key:'wave_period',dec:1}};
const NODES=[{code:'HN-01',name:'HAIKOU NORTH',lat:20.18,lon:110.36},{code:'HN-02',name:'QIONGZHOU EAST',lat:20.10,lon:110.75},{code:'HN-03',name:'WENCHANG NE',lat:19.92,lon:111.05},{code:'HN-04',name:'WENCHANG EAST',lat:19.55,lon:111.15},{code:'HN-05',name:'QIONGHAI EAST',lat:19.22,lon:110.95},{code:'HN-06',name:'WANNING EAST',lat:18.82,lon:110.82},{code:'HN-07',name:'LINGSHUI SE',lat:18.38,lon:110.42},{code:'HN-08',name:'SANYA EAST',lat:18.15,lon:109.78},{code:'HN-09',name:'SANYA SOUTH',lat:17.95,lon:109.48},{code:'HN-10',name:'YAZHOU SW',lat:18.12,lon:109.05},{code:'HN-11',name:'DONGFANG WEST',lat:18.95,lon:108.38},{code:'HN-12',name:'CHANGJIANG WEST',lat:19.32,lon:108.42},{code:'HN-13',name:'DANZHOU WEST',lat:19.65,lon:108.65},{code:'HN-14',name:'LINGAO NW',lat:19.95,lon:109.35}];
let islandRing=[[110.1065,20.0269],[110.7173,20.1487],[111.0713,19.6289],[110.6193,19.1520],[110.3675,18.6322],[109.7499,18.1933],[109.1747,18.2601],[108.6449,18.4867],[108.5911,19.1416],[108.8870,19.4897],[109.2556,19.8672],[109.7123,20.0174],[110.1065,20.0269]];
const map=L.map('map',{zoomControl:true,attributionControl:true,preferCanvas:true,minZoom:6,maxZoom:12}).setView(HAINAN_CENTER,7.55);
L.tileLayer('https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',{attribution:'&copy; OpenStreetMap &copy; CARTO',subdomains:'abcd',maxZoom:20,detectRetina:true}).addTo(map);
L.control.scale({imperial:false,position:'bottomright'}).addTo(map);
let boundaryLayer=null;
const markerLayer=L.layerGroup().addTo(map);
const state={gridData:[],nodeData:new Map(),activeLayer:'sst',timeIndex:0,selectedNode:null,particlesOn:true,demo:false,loadedAt:null,chartRange:'2W',chartMetric:'wave'};
const fieldCanvas=document.getElementById('fieldCanvas'),fieldCtx=fieldCanvas.getContext('2d');
const currentCanvas=document.getElementById('currentCanvas'),currentCtx=currentCanvas.getContext('2d');
let particles=[],seriesChart=null,renderQueued=false;
function status(msg,error=false,hideAfter=0){const el=document.getElementById('statusbar');el.textContent=msg;el.className='statusbar show'+(error?' error':'');if(hideAfter)setTimeout(()=>el.className='statusbar',hideAfter)}
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));const lerp=(a,b,t)=>a+(b-a)*t;
function mean(vals){const a=vals.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:NaN}
function palette(value,min,max,alpha=.70){const stops=[[75,128,255],[50,200,221],[102,230,145],[255,224,103],[255,127,80],[255,77,131]];let t=clamp((value-min)/(max-min),0,1)*(stops.length-1),i=Math.floor(t),f=t-i;if(i>=stops.length-1)i=stops.length-2,f=1;const a=stops[i],b=stops[i+1];return `rgba(${Math.round(lerp(a[0],b[0],f))},${Math.round(lerp(a[1],b[1],f))},${Math.round(lerp(a[2],b[2],f))},${alpha})`}
function ringArea(r){let a=0;for(let i=0,j=r.length-1;i<r.length;j=i++)a+=(r[j][0]*r[i][1]-r[i][0]*r[j][1]);return Math.abs(a/2)}
function pointInIsland(lat,lon){let inside=false;for(let i=0,j=islandRing.length-1;i<islandRing.length;j=i++){const xi=islandRing[i][0],yi=islandRing[i][1],xj=islandRing[j][0],yj=islandRing[j][1];const hit=((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/(yj-yi+1e-12)+xi);if(hit)inside=!inside}return inside}
async function loadBoundary(){try{const r=await fetch(BOUNDARY_URL);if(!r.ok)throw new Error('boundary '+r.status);const gj=await r.json();const rings=[];for(const f of gj.features||[]){const g=f.geometry;if(!g)continue;if(g.type==='Polygon')for(const p of g.coordinates)rings.push(p);if(g.type==='MultiPolygon')for(const poly of g.coordinates)for(const p of poly)rings.push(p)}const candidates=rings.filter(r=>r.some(([lon,lat])=>lat>17&&lat<21&&lon>108&&lon<112));if(candidates.length)islandRing=candidates.sort((a,b)=>ringArea(b)-ringArea(a))[0]}catch(e){console.warn('Boundary fallback',e)}if(boundaryLayer)map.removeLayer(boundaryLayer);boundaryLayer=L.polyline(islandRing.map(([lon,lat])=>[lat,lon]),{color:'#a9fff3',weight:2.0,opacity:.74,interactive:false,lineJoin:'round'}).addTo(map)}
function resizeCanvas(c,ctx){const r=map.getContainer().getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);c.style.width=r.width+'px';c.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function resizeAll(){resizeCanvas(fieldCanvas,fieldCtx);resizeCanvas(currentCanvas,currentCtx);queueFieldRender()}
function createGrid(){const pts=[],nLat=10,nLon=13;for(let i=0;i<nLat;i++)for(let j=0;j<nLon;j++){const lat=lerp(17.83,20.48,i/(nLat-1)),lon=lerp(108.25,111.38,j/(nLon-1));if(pointInIsland(lat,lon))continue;pts.push([lat,lon])}return pts}
function valueAt(d,key,ti){if(!d)return NaN;if(ti===0&&d.current&&Number.isFinite(d.current[key]))return d.current[key];const idx=Math.max(0,ti-1);return d.hourly&&d.hourly[key]?d.hourly[key][idx]:NaN}
function gridMeta(){return LAYERS[state.activeLayer]}
function nearestGrid(lat,lon){let best=null,bd=1e9;for(const d of state.gridData){const z=(d.latitude-lat)**2+(d.longitude-lon)**2;if(z<bd){bd=z;best=d}}return best}
function interpolateValue(lat,lon,key){let sw=0,sv=0;for(const d of state.gridData){const dy=d.latitude-lat,dx=(d.longitude-lon)*Math.cos(lat*Math.PI/180),dist2=dx*dx+dy*dy;if(dist2>1.1)continue;const v=valueAt(d,key,state.timeIndex);if(!Number.isFinite(v))continue;const w=1/(dist2+.018);sw+=w;sv+=w*v}return sw?sv/sw:NaN}
function queueFieldRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;renderField()})}
function renderField(){const w=map.getSize().x,h=map.getSize().y;fieldCtx.clearRect(0,0,w,h);if(!state.gridData.length)return;const meta=gridMeta(),step=7;for(let y=0;y<h;y+=step){for(let x=0;x<w;x+=step){const ll=map.containerPointToLatLng([x+step/2,y+step/2]);if(ll.lat<BOUNDS.minLat||ll.lat>BOUNDS.maxLat||ll.lng<BOUNDS.minLon||ll.lng>BOUNDS.maxLon)continue;const v=interpolateValue(ll.lat,ll.lng,meta.key);if(!Number.isFinite(v))continue;fieldCtx.fillStyle=palette(v,...meta.range,.42);fieldCtx.fillRect(x,y,step+1,step+1)}}fieldCtx.save();fieldCtx.globalCompositeOperation='destination-out';fieldCtx.beginPath();islandRing.forEach(([lon,lat],i)=>{const p=map.latLngToContainerPoint([lat,lon]);i?fieldCtx.lineTo(p.x,p.y):fieldCtx.moveTo(p.x,p.y)});fieldCtx.closePath();fieldCtx.fillStyle='#000';fieldCtx.fill();fieldCtx.restore()}
function currentVector(d){const speed=valueAt(d,'ocean_current_velocity',state.timeIndex)||0,deg=valueAt(d,'ocean_current_direction',state.timeIndex)||0,r=deg*Math.PI/180;return{speed,u:Math.sin(r)*speed,v:Math.cos(r)*speed,dir:deg}}
function randomOcean(){for(let k=0;k<100;k++){const lat=lerp(BOUNDS.minLat,BOUNDS.maxLat,Math.random()),lon=lerp(BOUNDS.minLon,BOUNDS.maxLon,Math.random());if(!pointInIsland(lat,lon))return{lat,lon,age:Math.random()*110}}return{lat:18,lon:108.3,age:0}}
function resetParticles(){resizeCanvas(currentCanvas,currentCtx);particles=Array.from({length:520},randomOcean)}
function animateParticles(){const w=map.getSize().x,h=map.getSize().y;currentCtx.globalCompositeOperation='destination-in';currentCtx.fillStyle='rgba(0,0,0,.91)';currentCtx.fillRect(0,0,w,h);currentCtx.globalCompositeOperation='source-over';if(state.particlesOn&&state.gridData.length){currentCtx.lineWidth=.8;for(const p of particles){const d=nearestGrid(p.lat,p.lon),v=currentVector(d);if(!d||!Number.isFinite(v.speed)){Object.assign(p,randomOcean());continue}const old=map.latLngToContainerPoint([p.lat,p.lon]),visual=.00125;p.lon+=v.u*visual/Math.max(.35,Math.cos(p.lat*Math.PI/180));p.lat+=v.v*visual;p.age++;if(p.age>150||p.lat<BOUNDS.minLat||p.lat>BOUNDS.maxLat||p.lon<BOUNDS.minLon||p.lon>BOUNDS.maxLon||pointInIsland(p.lat,p.lon)){Object.assign(p,randomOcean());continue}const ne=map.latLngToContainerPoint([p.lat,p.lon]);if(old.x<-10||old.y<-10||old.x>w+10||old.y>h+10)continue;currentCtx.strokeStyle=`rgba(143,243,231,${clamp(.20+v.speed*.27,.22,.82)})`;currentCtx.beginPath();currentCtx.moveTo(old.x,old.y);currentCtx.lineTo(ne.x,ne.y);currentCtx.stroke()}}else currentCtx.clearRect(0,0,w,h);requestAnimationFrame(animateParticles)}
async function fetchGrid(){const pts=createGrid(),lat=pts.map(p=>p[0].toFixed(3)).join(','),lon=pts.map(p=>p[1].toFixed(3)).join(',');const q=new URLSearchParams({latitude:lat,longitude:lon,current:VARIABLES.join(','),hourly:VARIABLES.join(','),forecast_hours:'72',timezone:'Asia/Shanghai',cell_selection:'sea'});const r=await fetch(`${API}?${q}`);if(!r.ok)throw new Error('grid '+r.status);const j=await r.json();return(Array.isArray(j)?j:[j]).map((d,i)=>({...d,requested:pts[i]}))}
async function fetchNodes(){const lat=NODES.map(n=>n.lat).join(','),lon=NODES.map(n=>n.lon).join(',');const q=new URLSearchParams({latitude:lat,longitude:lon,current:VARIABLES.join(','),hourly:VARIABLES.join(','),past_days:'30',forecast_days:'8',timezone:'Asia/Shanghai',cell_selection:'sea'});const r=await fetch(`${API}?${q}`);if(!r.ok)throw new Error('nodes '+r.status);const j=await r.json(),arr=Array.isArray(j)?j:[j];const m=new Map();arr.forEach((d,i)=>m.set(NODES[i].code,{...d,node:NODES[i]}));return m}
function demoNodeData(){const m=new Map(),now=new Date();NODES.forEach((n,i)=>{const hourly={time:[],sea_surface_temperature:[],ocean_current_velocity:[],ocean_current_direction:[],wave_height:[],wave_direction:[],wave_period:[]};for(let h=-30*24;h<8*24;h++){const t=new Date(now.getTime()+h*3600000),phase=i*.5+h/17;hourly.time.push(t.toISOString().slice(0,16));hourly.sea_surface_temperature.push(29.0+.7*Math.sin(phase/5)+.25*Math.sin(h/24));hourly.ocean_current_velocity.push(.35+.5*Math.abs(Math.sin(phase/4)));hourly.ocean_current_direction.push((80+110*Math.sin(phase/7)+360)%360);hourly.wave_height.push(.55+.85*Math.abs(Math.sin(phase/6))+.35*Math.max(0,Math.sin((h+80)/26)));hourly.wave_direction.push((135+70*Math.sin(phase/9)+360)%360);hourly.wave_period.push(5.5+2.1*Math.abs(Math.cos(phase/8)))}const k=hourly.time.length-8*24;m.set(n.code,{node:n,latitude:n.lat,longitude:n.lon,current:{sea_surface_temperature:hourly.sea_surface_temperature[k],ocean_current_velocity:hourly.ocean_current_velocity[k],ocean_current_direction:hourly.ocean_current_direction[k],wave_height:hourly.wave_height[k],wave_direction:hourly.wave_direction[k],wave_period:hourly.wave_period[k]},hourly})});return m}
function demoGridData(){const pts=createGrid(),now=new Date();return pts.map(([lat,lon],i)=>{const base=29.1+.85*Math.sin((lat-18.2)*1.1)-.35*Math.cos((lon-109.7)*1.7),curr=.25+.75*Math.abs(Math.sin(lon*1.7+lat*.7)),dir=(45+85*Math.sin(lat*2.4+lon*.4)+360)%360,wave=.5+1.2*Math.abs(Math.sin(lon*.9-lat*.5)),period=5.3+2.5*Math.abs(Math.cos(lat*.8+lon)),hourly={time:[],sea_surface_temperature:[],ocean_current_velocity:[],ocean_current_direction:[],wave_height:[],wave_direction:[],wave_period:[]};for(let h=0;h<72;h++){hourly.time.push(new Date(now.getTime()+h*3600000).toISOString());hourly.sea_surface_temperature.push(base+.28*Math.sin(h/12+i*.15));hourly.ocean_current_velocity.push(curr*(.82+.2*Math.sin(h/8+i)));hourly.ocean_current_direction.push((dir+14*Math.sin(h/10))%360);hourly.wave_height.push(wave*(.86+.28*Math.cos(h/16+i*.2)));hourly.wave_direction.push((145+40*Math.sin(i+h/10)+360)%360);hourly.wave_period.push(period+.6*Math.sin(h/11+i))}return{latitude:lat,longitude:lon,current:{sea_surface_temperature:base,ocean_current_velocity:curr,ocean_current_direction:dir,wave_height:wave,wave_direction:145,wave_period:period},hourly}})}
async function load(){status('Connecting to live marine model…');await loadBoundary();try{const[g,n]=await Promise.all([fetchGrid(),fetchNodes()]);state.gridData=g;state.nodeData=n;state.demo=false;state.loadedAt=new Date();document.getElementById('liveLabel').textContent='LIVE MODEL';document.getElementById('modelNote').textContent='Open-Meteo Marine · updated '+state.loadedAt.toLocaleString('en-GB',{hour12:false});status('Marine data updated',false,1500)}catch(e){console.warn(e);state.gridData=demoGridData();state.nodeData=demoNodeData();state.demo=true;state.loadedAt=new Date();document.getElementById('liveLabel').textContent='DEMO FALLBACK';document.getElementById('modelNote').textContent='Live API unavailable. Clearly labelled demo fallback is active.';status('Live API unavailable — demo fallback active',true,4200)}renderMarkers();renderNodeList();updateStats();updateLegend();updateTime();queueFieldRender();resetParticles()}
