function nodeValue(nd,layer=state.activeLayer){const m=LAYERS[layer],v=nd?.current?.[m.key];return Number.isFinite(v)?v:NaN}
function markerHTML(value,selected){const meta=gridMeta(),color=palette(value,...meta.range,1);return `<div class="node-marker${selected?' selected':''}" style="background:${color}"></div>`}
function renderMarkers(){markerLayer.clearLayers();for(const n of NODES){const nd=state.nodeData.get(n.code),v=nodeValue(nd),icon=L.divIcon({className:'node-marker-wrap',html:markerHTML(v,state.selectedNode?.code===n.code),iconSize:[18,18],iconAnchor:[9,9]});const m=L.marker([n.lat,n.lon],{icon});m.bindTooltip(`<b>${n.code} · ${n.name}</b><br>${Number.isFinite(v)?v.toFixed(gridMeta().dec):'--'} ${gridMeta().unit}<br><span style="color:#8eaab5">Click for live time series</span>`,{className:'ocean-tip',direction:'top'});m.on('click',()=>selectNode(n,true));m.addTo(markerLayer)}}
function renderNodeList(){const el=document.getElementById('nodeList');el.innerHTML='';for(const n of NODES){const nd=state.nodeData.get(n.code),v=nodeValue(nd),meta=gridMeta(),b=document.createElement('button');b.className='node-row'+(state.selectedNode?.code===n.code?' active':'');b.innerHTML=`<span class="node-code">${n.code}</span><span class="node-name">${n.name}</span><span class="node-value">${Number.isFinite(v)?v.toFixed(meta.dec):'--'}</span>`;b.onclick=()=>selectNode(n,false);el.appendChild(b)}}
function selectNode(n,openChart=false){state.selectedNode=n;map.flyTo([n.lat,n.lon],8.7,{duration:.55});renderMarkers();renderNodeList();updateStats();if(openChart)openSeries()}
function updateLegend(){const m=gridMeta();document.getElementById('legendTitle').textContent=m.label;['l0','l1','l2','l3','l4'].forEach((id,i)=>document.getElementById(id).textContent=m.ticks[i])}
function updateStats(){const meta=gridMeta();let source=[],label='Hainan coastal waters',coords='Regional mean',type='REGIONAL FIELD',code='HN';if(state.selectedNode){const nd=state.nodeData.get(state.selectedNode.code);if(nd)source=[nd];label=state.selectedNode.name;coords=`${state.selectedNode.lat.toFixed(2)}°N, ${state.selectedNode.lon.toFixed(2)}°E`;type='MODEL NODE';code=state.selectedNode.code}else source=state.gridData;const avg=k=>mean(source.map(d=>valueAt(d,k,state.timeIndex)));const val=avg(meta.key),curr=avg('ocean_current_velocity'),dir=avg('ocean_current_direction'),wave=avg('wave_height'),period=avg('wave_period');document.getElementById('focusType').textContent=type;document.getElementById('focusCode').textContent=code;document.getElementById('focusName').textContent=label;document.getElementById('focusCoords').textContent=coords;document.getElementById('heroValue').textContent=Number.isFinite(val)?val.toFixed(meta.dec):'--';document.getElementById('heroUnit').textContent=meta.unit;document.getElementById('currentSpeed').textContent=Number.isFinite(curr)?curr.toFixed(2):'--';document.getElementById('currentDirection').textContent=Number.isFinite(dir)?Math.round(dir):'--';document.getElementById('waveHeight').textContent=Number.isFinite(wave)?wave.toFixed(2):'--';document.getElementById('wavePeriod').textContent=Number.isFinite(period)?period.toFixed(1):'--'}
function updateTime(){const h=state.timeIndex,d=new Date(Date.now()+Math.max(0,h-1)*3600000);document.getElementById('timeValue').textContent=h===0?'NOW':`+${h}h · ${d.toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false})}`}
const METRICS={wave:{key:'wave_height',dir:'wave_direction',label:'Wave Height',unit:'m',dec:2},sst:{key:'sea_surface_temperature',dir:'wave_direction',label:'Sea Surface Temperature',unit:'°C',dec:1},current:{key:'ocean_current_velocity',dir:'ocean_current_direction',label:'Ocean Current Velocity',unit:'km/h',dec:2},period:{key:'wave_period',dir:'wave_direction',label:'Wave Period',unit:'s',dec:1}};
const rangeHours={"1D":[18,6],"3D":[48,24],"1W":[120,48],"2W":[288,48],"1M":[528,192],"ALL":[99999,99999]};
function parseTimes(times){return times.map(t=>new Date(t).getTime())}
function chartSlice(nd){const times=parseTimes(nd.hourly.time),now=Date.now(),r=rangeHours[state.chartRange]||rangeHours['2W'];let idx=[];for(let i=0;i<times.length;i++)if(times[i]>=now-r[0]*3600000&&times[i]<=now+r[1]*3600000)idx.push(i);if(!idx.length)idx=times.map((_,i)=>i);return idx}
const nowLinePlugin={id:'nowLine',afterDraw(chart){const x=chart.scales.x;if(!x)return;const px=x.getPixelForValue(Date.now());if(px<x.left||px>x.right)return;const c=chart.ctx;c.save();c.strokeStyle='#39718f';c.lineWidth=1.5;c.setLineDash([7,6]);c.beginPath();c.moveTo(px,chart.chartArea.top);c.lineTo(px,chart.chartArea.bottom);c.stroke();c.setLineDash([]);c.fillStyle='#39718f';c.font='600 11px Inter, sans-serif';c.textAlign='center';c.fillText(new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}),px,chart.chartArea.top-8);c.restore()}};
function drawDirection(nd,idx){const c=document.getElementById('directionCanvas'),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);const metric=METRICS[state.chartMetric],arr=nd.hourly[metric.dir]||[],count=Math.min(30,idx.length),step=Math.max(1,Math.floor(idx.length/count));ctx.strokeStyle='#39779b';ctx.fillStyle='#39779b';ctx.lineWidth=1.4;for(let k=0;k<idx.length;k+=step){const i=idx[k],deg=arr[i];if(!Number.isFinite(deg))continue;const x=(k/(idx.length-1||1))*(r.width-18)+9,y=r.height/2,ang=(deg-90)*Math.PI/180,len=13,tx=x+Math.cos(ang)*len,ty=y+Math.sin(ang)*len;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(tx,ty);ctx.stroke();const ah=4;ctx.beginPath();ctx.moveTo(tx,ty);ctx.lineTo(tx+Math.cos(ang+2.55)*ah,ty+Math.sin(ang+2.55)*ah);ctx.lineTo(tx+Math.cos(ang-2.55)*ah,ty+Math.sin(ang-2.55)*ah);ctx.closePath();ctx.fill()}}
function renderChart(){if(!state.selectedNode)return;const nd=state.nodeData.get(state.selectedNode.code);if(!nd?.hourly)return;const metric=METRICS[state.chartMetric],idx=chartSlice(nd),times=parseTimes(nd.hourly.time),vals=nd.hourly[metric.key],data=idx.map(i=>({x:times[i],y:vals[i]})).filter(p=>Number.isFinite(p.y));document.getElementById('chartTitle').textContent=`${state.selectedNode.code} · ${state.selectedNode.name}`;document.getElementById('chartSub').textContent=`MODEL NODE · ${state.selectedNode.lat.toFixed(2)}°N, ${state.selectedNode.lon.toFixed(2)}°E · ${metric.label}`;document.getElementById('chartStamp').innerHTML=`<strong>${state.demo?'DEMO FALLBACK':'LIVE MODEL'}</strong> · ${state.loadedAt?state.loadedAt.toLocaleString('en-GB',{hour12:false}):''}`;if(seriesChart)seriesChart.destroy();seriesChart=new Chart(document.getElementById('seriesChart'),{type:'line',data:{datasets:[{label:metric.label,data,borderColor:'#39779b',backgroundColor:'rgba(57,119,155,.08)',pointRadius:2.2,pointHoverRadius:4,borderWidth:2.3,tension:.08,fill:false}]},plugins:[nowLinePlugin],options:{responsive:true,maintainAspectRatio:false,animation:false,parsing:false,interaction:{mode:'nearest',intersect:false},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${metric.label}: ${c.parsed.y.toFixed(metric.dec)} ${metric.unit}`}}},scales:{x:{type:'linear',grid:{color:'#e1e7ea'},ticks:{color:'#333',maxTicksLimit:8,callback:v=>new Date(v).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',hour12:false})}},y:{position:'right',grid:{color:'#dfe6e9'},ticks:{color:'#333'},title:{display:true,text:`${metric.label} (${metric.unit})`,color:'#5d656a',font:{size:12,weight:'600'}}}}}});drawDirection(nd,idx)}
function openSeries(){if(!state.selectedNode)state.selectedNode=NODES[0];state.chartMetric=state.activeLayer;document.querySelectorAll('.metric-btn').forEach(b=>b.classList.toggle('active',b.dataset.metric===state.chartMetric));document.getElementById('chartModal').classList.add('open');setTimeout(renderChart,40)}
document.querySelectorAll('.layerbtn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.layerbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.activeLayer=b.dataset.layer;updateLegend();updateStats();renderMarkers();renderNodeList();queueFieldRender()}));
document.getElementById('particleSwitch').onclick=e=>{state.particlesOn=!state.particlesOn;e.currentTarget.classList.toggle('on',state.particlesOn);if(!state.particlesOn)currentCtx.clearRect(0,0,map.getSize().x,map.getSize().y)};
document.getElementById('timeSlider').addEventListener('input',e=>{state.timeIndex=+e.target.value;updateStats();updateTime();renderMarkers();renderNodeList();queueFieldRender()});
document.getElementById('refreshBtn').onclick=load;document.getElementById('openSeriesBtn').onclick=openSeries;document.getElementById('closeChart').onclick=()=>document.getElementById('chartModal').classList.remove('open');document.getElementById('chartModal').addEventListener('click',e=>{if(e.target.id==='chartModal')e.currentTarget.classList.remove('open')});
document.querySelectorAll('.zoom-btn').forEach(b=>b.onclick=()=>{state.chartRange=b.dataset.range;document.querySelectorAll('.zoom-btn').forEach(x=>x.classList.toggle('active',x===b));renderChart()});
document.querySelectorAll('.metric-btn').forEach(b=>b.onclick=()=>{state.chartMetric=b.dataset.metric;document.querySelectorAll('.metric-btn').forEach(x=>x.classList.toggle('active',x===b));renderChart()});
window.addEventListener('keydown',e=>{if(e.key==='Escape')document.getElementById('chartModal').classList.remove('open')});
map.on('move zoom resize',()=>{resizeAll()});window.addEventListener('resize',()=>{resizeAll();if(document.getElementById('chartModal').classList.contains('open'))setTimeout(renderChart,80)});
resizeAll();resetParticles();animateParticles();load();
